### ISSUE TITLE
USER STORY: First Heroku Deployment

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#1]
As a **developer** I can **deploy my project on Heroku** so that **it can be seen and used by other users**

## Tasks
- [x] Task 1 - Create new app on Heroku
- [x] Task 2 - Create new instance on ElephantSql dashboard
- [x] Task 3 - Create env.py file and change settings.py as required
- [x] Task 4 - Migrate changes to database
- [x] Task 5 - Add config vars on Heroku
- [x]  Task 6 - Create procfile
- [x] Task 7 - Deploy Branch in Heroku

**Comment by seanj06** [comment]
App successfully deployed to heroku - [4fc6f57](https://github.com/seanj06/P4-Sports-Expert/commit/4fc6f57ea26811b500bcba6f0907e25e41e3f7b7)
