### ISSUE TITLE
USER STORY:Create Superuser

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#10]
As a **developer** I can **create a superuser** so that **i can manage my application from the admin panel**

## Tasks
- [x] Task 1 - Create Superuser from command line
- [x] Task 2 - Install Summernote from command line
- [x] Task 3 - Run project with /admin added to url to make sure superuser can login

**Comment by seanj06** [comment]
Allauth installed and admin panel checked - [3bd8927](https://github.com/seanj06/P4-Sports-Expert/commit/3bd89275ee6778dd47083f3990bd8ca99a097816)

**Comment by seanj06** [comment]
Summernote installed and added to installed apps in settings.py - [f5bb7cd](https://github.com/seanj06/P4-Sports-Expert/commit/f5bb7cd6519192ac6c23c3090fba48489b1eb1d9)
