### ISSUE TITLE
USER STORY:Cloudinary

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#12]
As a **developer** I can **install cloudinary** so that **all my images can still be displayed on my site after being deployed**

## Tasks
- [ ] Task 1 - Set up cloudinary account to get api var
- [ ] Task 2 - Install cloudnary in workspace
- [ ] Task 3 - add config var to env.py file and heroku
- [ ] Task 4 - Add relevant variables to settings.py

**Comment by seanj06** [comment]
Cloudinary installed and all variables added in settings.py - [8fc3000](https://github.com/seanj06/P4-Sports-Expert/commit/8fc3000810860833ac97b7c881431df88f0a0d71)
