### ISSUE TITLE
USER STORY:Home page

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#14]
As a **user** I can **visit the homepage** so that **I can log into my account and navigate to different parts of the site**

## Tasks
- [x] Task 1 - Create view to homepage
- [x] Task 2 - Create navbar 
- [x] Task 3 - Add sign in/sign up links to navbar

**Comment by seanj06** [comment]
Homepage created with view - [5a10cf9](https://github.com/seanj06/P4-Sports-Expert/commit/5a10cf93513f45568466afe5bf1f7f62fc8c1799)

Bootstrap navbar added with links - [3e84feb](https://github.com/seanj06/P4-Sports-Expert/commit/3e84febb7459482bfeb9db6df4641c0c9f7a82d1)
