### ISSUE TITLE
USER STORY: Home Page styling

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#15]
As a **developer** I can **style the home page** so that **it is visually appealing for new and frequent users**

## Tasks
- [x] Task 1 -Style homepage using bootstrap
- [x] Task 2 - Add custom fonts using google fonts
- [x] Task 3 - Add introduction section 
- [x] Task 4 - Add active class to navbar

**Comment by seanj06** [comment]
Introduction section added to home page - [da21efe](https://github.com/seanj06/P4-Sports-Expert/commit/da21efe386567615d9f1db82882058d69f08d2e4)

**Comment by seanj06** [comment]
Active class added to navbar - [e6bd695](https://github.com/seanj06/P4-Sports-Expert/commit/e6bd69547f43dcd1c508931f99630f59b0dbba19)
