### ISSUE TITLE
USER STORY: Django Forms

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#17]
As a **developer** I can **create django forms** so that **user database input can be validated and handled correctly**

## Tasks
- [x] Task 1 - Create forms.py file
- [x] Task 2 - Create a form linking to database model
- [x] Task 3 - Define which fields are needed from model
