### ISSUE TITLE
USER STORY:Create new django project and app

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#2]
As a **developer** I can **create a new Django project correctly** so that **my project can be built in the correct way**

## Tasks
- [x] Task 1 - Create new django project from command line
- [x] Task 2 - Create new app inside project andadd to installed apps on settings.py
- [x] Task 3 - Migrate all changes to database
- [x] Task 4 - Run app on server to make sure it was created successfully

**Comment by seanj06** [comment]
Project created and server run to make sure app was correctly installed - [b6338d3](https://github.com/seanj06/P4-Sports-Expert/commit/b6338d35869a468eff9b5bcf4f7d6ad2b46fb3e0)
