### ISSUE TITLE
USER STORY:Delete Blog Post

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#24]
As a **user** I can **delete my blog post** so that **I can remove any posts i no longer want**

## Tasks
- [x] Task 1 - Create delete button on detail view page
- [x] Task 2 - Ensure only logged in users can access delete button
- [x] Task 3 - Write code to ensure when delete button is pressed, data is removed from database

**Comment by seanj06** [comment]
Delete button created - [bbd7f84](https://github.com/seanj06/P4-Sports-Expert/commit/bbd7f8446630401079884be201e6f981b2eba69e)

**Comment by seanj06** [comment]
Code written to ensure only logged users who own the post can delete - [https://github.com/seanj06/P4-Sports-Expert/commit/00ff7dec021e75e53f9eb5ec1033e6be3af40088](https://github.com/seanj06/P4-Sports-Expert/commit/00ff7dec021e75e53f9eb5ec1033e6be3af40088)
