### ISSUE TITLE
USER STORY:User Messages

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#26]
As a **developer** I can **add custom user messages** so that **the user knows the action they performed has been successfull or failed**

## Tasks
- [x] Task 1 - Import messages in files where needed
- [x] Task 2 - Add message tags to settings.py
- [x] Task 3 - Add messages to html files where needed
- [x] Task 4 - Add. javascript timeout function

**Comment by seanj06** [comment]
Messages imported and message tags added in settings.py - [7b40c7d](https://github.com/seanj06/P4-Sports-Expert/commit/7b40c7d42f6e4c6e430841c4a6f42336d5be682d)

**Comment by seanj06** [comment]
Messages container added to base.html - [https://github.com/seanj06/P4-Sports-Expert/commit/fcdd14186a3d378be58bf943785ab9eb5a34cd3f](https://github.com/seanj06/P4-Sports-Expert/commit/fcdd14186a3d378be58bf943785ab9eb5a34cd3f)

**Comment by seanj06** [comment]
Success messages added to All class based views - [09fa19b](https://github.com/seanj06/P4-Sports-Expert/commit/09fa19be637ac0f9f1aea8a2d9839eadc6296bdc)
