### ISSUE TITLE
USER STORY:Create a profile

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#27]
As a **user** I can **create a profile** so that **I can keep track of my blogs**

## Tasks
- [x] Task 1 - Create Profile app
- [x] Task 2 - Add user one to one model
- [x] Task 3 - Create profile page template
- [x] Task 4 - Create profile view

**Comment by seanj06** [comment]
Profile app created - [https://github.com/seanj06/P4-Sports-Expert/commit/ff680fedf12222a840dab7cec5859d84b550d024](https://github.com/seanj06/P4-Sports-Expert/commit/ff680fedf12222a840dab7cec5859d84b550d024)

**Comment by seanj06** [comment]
Django signals added to automatically create profile on account creation - [3abe18b](https://github.com/seanj06/P4-Sports-Expert/commit/3abe18be79adaa7e1948652a90b5ec4b4c7c723a)
