### ISSUE TITLE
USER STORY:Django package installation

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#3]
As a **developer** I can **install the needed librarys and packages** so that **my project is set up correctly**

## Tasks
- [x] Task 1 - Install Django + Heroku server from command line
- [x] Task 2 - Install PostgreSql database from command line
- [x] Task 3 - Install Cloudinary from command line
- [x] Task 4 - Create requirements.txt file

**Comment by seanj06** [comment]
All packages installed - [64203e7](https://github.com/seanj06/P4-Sports-Expert/commit/b6338d35869a468eff9b5bcf4f7d6ad2b46fb3e0)
