### ISSUE TITLE
USER STORY:Profile Form

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#31]
As a **user** I can **add my profile info by filling out a form** so that **I can save the info to my profile**

## Tasks
- [x] Task 1 - Create forms.py file in profiles app
- [x] Task 2 - Create form that is linked to Profile model
- [x] Task 3 - Create view for form

**Comment by seanj06** [comment]
User profile automatically added with django signals

User able to edit profile with form - [6e704c2](https://github.com/seanj06/P4-Sports-Expert/commit/6e704c2a804bc3b246262e5e331fc1d2f4d789bd)
