### ISSUE TITLE
USER STORY:Blog Page

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#32]
As a **developer** I can **style the blog page** so that **the user gets a good u/x experience**

## Tasks
- [x] Task 1 - Add code so only 6 blogs are shown per page
- [x] Task 2 - Ensure blog cards have correct information shown
- [x] Task 3 - Change placeholder image depending on category

**Comment by seanj06** [comment]
Pagination added to blog page[17009b5](https://github.com/seanj06/P4-Sports-Expert/commit/17009b58d23dc2ed6417f3b6de8ab4c66cd9bfdf)

**Comment by seanj06** [comment]
Added Date created and category fields to blog card - [5532c09](https://github.com/seanj06/P4-Sports-Expert/commit/5532c09233cf2370e25d83ea820af3c95e89e7f3)

**Comment by seanj06** [comment]
Placeholder image changes depending on user picked category - [f0e5caf](https://github.com/seanj06/P4-Sports-Expert/commit/f0e5caf54d707d3dfb40b9fc44197edbafc02e38)
