### ISSUE TITLE
USER STORY:Forms

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#33]
As a **developer** I can **style the user forms** so that **they match the design of the rest of the site**

## Tasks
- [x] Task 1 - Ensure sign up, log in ,log out edit blog and add blog pages design matches rest of site
- [x] Task 2 - Ensure success messages dont push down content
- [x] Task 3 - Ensure all success urls bring user to reverse page

**Comment by seanj06** [comment]
All forms styled to match site design - [2e6381f](https://github.com/seanj06/P4-Sports-Expert/commit/2e6381f1341bb9a685dbcdf6607186fe49201bde)

**Comment by seanj06** [comment]
Absolute position given to success messages so messages dont push down content - [b08a1ca](https://github.com/seanj06/P4-Sports-Expert/commit/b08a1cafb441b857770ef0b828c78cece10b6405)

**Comment by seanj06** [comment]
Code added in editprofile view to take user back to previous page - [9b52ed5](https://github.com/seanj06/P4-Sports-Expert/commit/9b52ed5d07222b266ac72c82100f8c6f7001788b)

**Comment by seanj06** [comment]
Code added in deletecomment view to take user back to previous page - [41ca8fc](https://github.com/seanj06/P4-Sports-Expert/commit/41ca8fc661c4cff8cc4c0fbac9176c56b433a830)
