### ISSUE TITLE
USER STORY:Footer

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#35]
As a **developer** I can **add a footer to my website** so that *I can display social media links and creation information**

## Tasks
- [x] Task 1 - Add footer to base.html
- [x] Task 2 - Add font awesome social media icons
- [x] Task 3 - Add creation information

**Comment by seanj06** [comment]
Footer added with font awesome links and creation information - [eefb81b](https://github.com/seanj06/P4-Sports-Expert/commit/eefb81b48fb504884b8f9493e8634512ad5ac608)

**Comment by seanj06** [comment]
Footer styled - [e8b77c7](https://github.com/seanj06/P4-Sports-Expert/commit/e8b77c7d1783d13ef19e7fcb74bff3ca7a1dd9f7)
