### ISSUE TITLE
USER STORY: Add comments to blogs

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#36]
As a **user** I can **comment on blogs** so that **i can interact with the site community**

## Tasks
- [x] Task 1 - Create comment model
- [x] Task 2 - Link comment model to user profile
- [x] Task 3 - Link model to blog posts
- [x] Task 4 - Render comments on template

**Comment by seanj06** [comment]
Comment model created - [7782aa7](https://github.com/seanj06/P4-Sports-Expert/commit/7782aa7a4186c366a56ed280ca8f94c3369a459a)

**Comment by seanj06** [comment]
View code added for user to comment on blog post and rendered to template - [https://github.com/seanj06/P4-Sports-Expert/commit/a0314ee4a9396dd76e96165598d44f08c0131944](https://github.com/seanj06/P4-Sports-Expert/commit/a0314ee4a9396dd76e96165598d44f08c0131944)
