### ISSUE TITLE
USER STORY: Add Models

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#4]
As a **developer** I can **add database models** so that **the database knows how to handle user data**

## Tasks
- [x] Task 1 - Import appropriate librarys at top of models.py file
- [x] Task 2 - Create a class based model
- [x] Task 3 - Add meta class to class based model
- [x] Task 4 - MIgrate changes to database

**Comment by seanj06** [comment]
BlogPost model created and changes migrated to database - [e815114](https://github.com/seanj06/P4-Sports-Expert/commit/e815114a3ccd09361eaacd54f98bd86a7327199b)
