### ISSUE TITLE
USER STORY:Create Templates

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#5]
As a **developer** I can **create templates** so that **users can see the website online**

## Tasks
- [x] Task 1 - Create templates folder
- [x] Task 2 - Create base.html file to hold base template code
- [x] Task 3 - Create base html template code
- [x] Task 4 - Create news urls.py file and enter new path

**Comment by seanj06** [comment]
Base.html file created and bootstrap content added - [3e84feb](https://github.com/seanj06/P4-Sports-Expert/commit/3e84febb7459482bfeb9db6df4641c0c9f7a82d1)

Url app file created and path added to home page - [5a10cf9](https://github.com/seanj06/P4-Sports-Expert/commit/5a10cf93513f45568466afe5bf1f7f62fc8c1799)
