### ISSUE TITLE
USER STORY:Create an account

### ISSUE THREAD

**Issue by seanj06** [seanj06/P4-Sports-Expert#6]
As a **User** I can **create an account** so that **I can create a blog post**

## Tasks
- [x] Task 1 - Install allauth so user can create an account
- [x] Task 2 - Create Make a post page that user can only access while logged in
- [x] Task 3 - Set up code so users post is saved to database

**Comment by seanj06** [comment]
Allauth installed - [https://github.com/seanj06/P4-Sports-Expert/commit/3bd89275ee6778dd47083f3990bd8ca99a097816](3bd8927)

**Comment by seanj06** [comment]
Add blog page created and code added to ensure only logged in users can access - [77f3686](https://github.com/seanj06/P4-Sports-Expert/commit/77f368639c4b1f4b79e9378bc8966a5f31f12b8b)
